### ISSUE TITLE
Add drag & drop support

### ISSUE THREAD

**Issue by FluentCoding** [frankborden/slippilab#3]
seems like there is no drag & drop support for slippi replays

**Comment by frankborden** [comment]
added and released drag/drop support for 1+ files. Directories seems tough, it may need to wait for file system access API to be in more browsers

**Comment by FluentCoding** [comment]
awesome! maybe zip support could be sick as well.

**Comment by frankborden** [comment]
Done. Already had some unzip code around for animations
