### ISSUE TITLE
website not playing replays. stuck at frame 10 or 11 and not showing characters.

### ISSUE THREAD

**Issue by reelguy** [frankborden/slippilab#40]
I load a replay, nothing plays, no characters, nothing.
![image](https://user-images.githubusercontent.com/77411480/192087894-9feba8a2-aba0-42ee-bb25-18b15021e399.png)

**Comment by frankborden** [comment]
Thanks for the report. That is strange. Does the demo work for you? https://slippilab.com/sample

if that works or other files work, can you send me the file that doesn’t work?

if nothing works, can you let me know what browser and operating system you are using? And the browser version. I have heard older browsers have had issues.

**Comment by reelguy** [comment]
The Sample doesn't work either. It works up until about frame 120 - 135 (different every playback) but after that it just freezes.

I am using Firefox 105.0.1 (64-bit) on Windows 10.0.19044 Build 19044.

**Comment by frankborden** [comment]
My dependency zip.js had a data race bug that is fixed by a recent version. It must have been broken when I bumped the version at some point. Fix is pushed and verified on firefox on windows11 and mac.
