### ISSUE TITLE
Unable to upload to Slippilab

### ISSUE THREAD

**Issue by pastadudes** [frankborden/slippilab#54]
OS: Windows 10
Browser: Firefox 133.0.3
![image](https://github.com/user-attachments/assets/5b4531f1-ca18-4964-a7bc-3b1b104e6eb7)
XHRPOST
https://slippilab.com/api/replay
[HTTP/3 500  4618ms]

Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by frankborden** [comment]
thanks a lot for letting me know, looks like it was down for a few weeks. I don't really know exactly why it broke from my last deploy, but I think I fixed it and was able to upload again.
